version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "crimeanBilling"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network

  app:
    image: ${BACKEND_IMAGE}
    container_name: app
    environment:
      - "ASPNETCORE_ENVIRONMENT=Release" 
      - "DATABASE_CONNECTION_STRING=host=postgres;Port=5432;Database=crimeanBilling;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
      - "MAIL_BOX_LOGIN=${MAIL_BOX_LOGIN}"
      - "MAIL_BOX_PASSWORD=${MAIL_BOX_PASSWORD}"
    ports:
      - 8080:8080
      - 4443:443
    depends_on:
      - postgres
    networks:
      - my-network

  front-manager-page:
    image: ${FRONT_MANAGER_IMAGE}
    container_name: front-manager-page
    depends_on:
      - app
    ports:
      - 1337:80
    networks:
      - my-network

  front-user-page:
    image: ${FRONT_USER_IMAGE}
    container_name: front-user-page
    depends_on:
      - app
    ports:
      - 1338:80
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./crimean-billing.work.gd.crt:/etc/nginx/crimean-billing.work.gd.crt
      - ./crimean-billing.work.gd.key:/etc/nginx/crimean-billing.work.gd.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
      - front-manager-page
      - front-user-page
    networks:
      - my-network


volumes:
  stackup_postgres_data:

networks:
  my-network:
    driver: bridge