version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "crimeanBilling"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - stackup_postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network

  app:
    image: ${BACKEND_IMAGE}
    container_name: app
    environment:
      - ASPNETCORE_ENVIRONMENT = Release 
      - "DATABASE_CONNECTION_STRING=host=postgres;Port=5432;Database=crimeanBilling;User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
    ports:
      - 8080:8080
      - 443:443
    depends_on:
      - postgres
    networks:
      - my-network

  front:
    image: ${FRONT_IMAGE}
    container_name: front
    depends_on:
      - app
    ports:
      - 1337:80
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
      - front
    networks:
      - my-network


volumes:
  stackup_postgres_data:

networks:
  my-network:
    driver: bridge